# Generated by Django 3.2.16 on 2026-03-01 09:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый таможенный орган', max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{4}000$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Таможня',
                'verbose_name_plural': 'Таможни',
            },
        ),
        migrations.CreateModel(
            name='CustPlace1Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Субъект учета для т.органа 1-го типа',
                'verbose_name_plural': 'Субъекты учета для т.органа 1-го типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlace1Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Субъект эксплуатации для т.органа 1-го типа',
                'verbose_name_plural': 'Субъекты эксплуатации для т.органа 1-го типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlaceToLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_for_cust', models.BooleanField(default=False, verbose_name='Флаг приоритетности')),
            ],
            options={
                'verbose_name': 'Отношение т.органа к локации эксплуатации',
                'verbose_name_plural': 'Отношения т.органа к локации эксплуатации',
            },
        ),
        migrations.CreateModel(
            name='CustPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый таможенный орган', max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Таможенный пост',
                'verbose_name_plural': 'Таможенные посты',
            },
        ),
        migrations.CreateModel(
            name='LocationOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ztk', models.BooleanField(default=False, verbose_name='Является ли ЗТК')),
            ],
            options={
                'verbose_name': 'объект локации',
                'verbose_name_plural': 'объекты локации',
            },
        ),
        migrations.CreateModel(
            name='Mmpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ММПО',
                'verbose_name_plural': 'объекты ММПО',
            },
        ),
        migrations.CreateModel(
            name='Oez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ОЭЗ',
                'verbose_name_plural': 'объекты ОЭЗ',
            },
        ),
        migrations.CreateModel(
            name='Ppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tow_country', models.CharField(max_length=255, null=True, verbose_name='Сопредельное государство')),
            ],
            options={
                'verbose_name': 'объект пункта пропуска',
                'verbose_name_plural': 'объекты пунктов пропуска',
            },
        ),
        migrations.CreateModel(
            name='PprType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип пункта пропуска')),
            ],
            options={
                'verbose_name': 'объект типа пункта пропуска',
                'verbose_name_plural': 'объекты типа пунктов пропуска',
            },
        ),
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый таможенный орган', max_length=255, verbose_name='Название')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{2}00000$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Региональное таможенное управление',
                'verbose_name_plural': 'Региональные таможенные управления',
            },
        ),
        migrations.CreateModel(
            name='Ztk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ЗТК',
                'verbose_name_plural': 'объекты ЗТК',
            },
        ),
        migrations.AddConstraint(
            model_name='ztk',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_ztk_title'),
        ),
        migrations.AddField(
            model_name='ppr',
            name='pptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_pptype', to='custplaces.pprtype', verbose_name='Тип п. пропуска'),
        ),
        migrations.AddConstraint(
            model_name='oez',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_oez_title'),
        ),
        migrations.AddConstraint(
            model_name='mmpo',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_mmpo_title'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='custplaces',
            field=models.ManyToManyField(through='custplaces.CustPlaceToLocation', to='custplaces.CustPlace1Use'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='mmpo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmpos', to='custplaces.mmpo', verbose_name='Название ММПО'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='oez',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oezs', to='custplaces.oez', verbose_name='Название ОЭЗ'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='ppr',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pprs', to='custplaces.ppr', verbose_name='Название п.пропуска'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='ztk',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ztks', to='custplaces.ztk', verbose_name='Название ЗТК'),
        ),
        migrations.AddField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cust_post_to_cust_house', to='custplaces.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddField(
            model_name='custplacetolocation',
            name='cust_pl1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cp1', to='custplaces.custplace1use', verbose_name='т. орган_1'),
        ),
        migrations.AddField(
            model_name='custplacetolocation',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_location', to='custplaces.locationofuse', verbose_name='локация'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1use', to='custplaces.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1use', to='custplaces.custpost', verbose_name='Название поста'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1use', to='custplaces.rtu', verbose_name='Название РТУ'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1acc', to='custplaces.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1acc', to='custplaces.custpost', verbose_name='Название поста'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1acc', to='custplaces.rtu', verbose_name='Название РТУ'),
        ),
        migrations.AddField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_ch_to_rtu', to='custplaces.rtu', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddConstraint(
            model_name='ppr',
            constraint=models.UniqueConstraint(fields=('pptype', 'title', 'tow_country'), name='unique_type_title'),
        ),
        migrations.AddConstraint(
            model_name='locationofuse',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ppr__isnull', True), ('mmpo__isnull', True), ('oez__isnull', True), models.Q(('ztk__isnull', True), _negated=True)), models.Q(('ppr__isnull', True), ('mmpo__isnull', True), models.Q(('oez__isnull', True), _negated=True), ('ztk__isnull', True)), models.Q(('ppr__isnull', True), models.Q(('mmpo__isnull', True), _negated=True), ('oez__isnull', True), ('ztk__isnull', True)), models.Q(models.Q(('ppr__isnull', True), _negated=True), ('mmpo__isnull', True), ('oez__isnull', True), ('ztk__isnull', True)), _connector='OR'), name='Loc_Nullable'),
        ),
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(fields=('cust_pl1', 'loc'), name='unique_cp_loc'),
        ),
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_cust', True)), fields=('cust_pl1',), name='uniq_main_for_cp1'),
        ),
        migrations.AddConstraint(
            model_name='custplace1use',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rtu__isnull', True), ('custhouse__isnull', True), models.Q(('custpost__isnull', True), _negated=True)), models.Q(('rtu__isnull', True), models.Q(('custhouse__isnull', True), _negated=True), ('custpost__isnull', True)), models.Q(models.Q(('rtu__isnull', True), _negated=True), ('custhouse__isnull', True), ('custpost__isnull', True)), _connector='OR'), name='CP1UseNullable'),
        ),
        migrations.AddConstraint(
            model_name='custplace1acc',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rtu__isnull', True), ('custhouse__isnull', True), models.Q(('custpost__isnull', True), _negated=True)), models.Q(('rtu__isnull', True), models.Q(('custhouse__isnull', True), _negated=True), ('custpost__isnull', True)), models.Q(models.Q(('rtu__isnull', True), _negated=True), ('custhouse__isnull', True), ('custpost__isnull', True)), _connector='OR'), name='CP1AccNullable'),
        ),
    ]
