# Generated by Django 3.2.16 on 2026-10-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(condition=models.Q(('loc__isnull', True)), fields=('cust_pl1',), name='unique_custpl1_when_loc_is_null'),
        ),
    ]
