# Generated by Django 3.2.16 on 2026-02-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustPlace1Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, verbose_name='Код т.органа')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
                ('type', models.IntegerField(choices=[(1, 'РТУ'), (2, 'Таможня'), (3, 'Пост')])),
                ('upper_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_ch_to_rtu', to='app.custplace1acc', verbose_name='Вышестоящий т. орган')),
            ],
            options={
                'db_table': 'cust_place_1_acc',
                'ordering': ['id'],
            },
        ),
    ]
