# Generated by Django 3.2.16 on 2026-02-17 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtu',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.custplace1acc',),
        ),
        migrations.AlterField(
            model_name='custplace1acc',
            name='upper_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_ch_to_rtu', to='app.custplace1acc', verbose_name='Вышестоящий т. орган'),
        ),
    ]
