# Generated by Django 3.2.16 on 2025-01-08 15:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{4}000$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Таможня',
                'verbose_name_plural': 'Таможни',
            },
        ),
        migrations.CreateModel(
            name='CustPlace1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Т.орган первого типа',
                'verbose_name_plural': 'Т.органы первого типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlace2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
                ('level', models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], max_length=1, verbose_name='Уровень т.органа')),
            ],
            options={
                'verbose_name': 'Т.орган второго типа',
                'verbose_name_plural': 'Т.органы второго типа',
            },
        ),
        migrations.CreateModel(
            name='CustPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Таможенный пост',
                'verbose_name_plural': 'Таможенные посты',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Техническое средство',
                'verbose_name_plural': 'Технические средства',
            },
        ),
        migrations.CreateModel(
            name='OtherTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип источника имущества')),
            ],
            options={
                'verbose_name': 'Иной источник получения имущества',
                'verbose_name_plural': 'Иные источники получения имущества',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Субъект учета т.с.',
                'verbose_name_plural': 'Субъект учета т.с.',
            },
        ),
        migrations.CreateModel(
            name='Ppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pptype', models.CharField(choices=[('1', 'АПП'), ('2', 'ВПП'), ('3', 'ЖДПП'), ('4', 'МПП'), ('5', 'ППП'), ('6', 'РПП'), ('7', 'СПП')], max_length=1, verbose_name='Тип п. пропуска')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tow_country', models.CharField(max_length=255, null=True, verbose_name='Сопредельное государство')),
            ],
            options={
                'verbose_name': 'Пункт пропуска',
                'verbose_name_plural': 'Пункты пропуска',
            },
        ),
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{2}00000$')], verbose_name='Код т.органа')),
            ],
            options={
                'verbose_name': 'Региональное таможенное управление',
                'verbose_name_plural': 'Региональные таможенные управления',
            },
        ),
        migrations.AddConstraint(
            model_name='ppr',
            constraint=models.UniqueConstraint(fields=('pptype', 'title'), name='unique_type_title'),
        ),
        migrations.AddField(
            model_name='owner',
            name='custplace1',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces1', to='core.custplace1', verbose_name='Субъект учета типа <т.орган первого типа>'),
        ),
        migrations.AddField(
            model_name='owner',
            name='custplace2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces2', to='core.custplace2', verbose_name='Субъект учета типа <т.орган второго типа>'),
        ),
        migrations.AddField(
            model_name='owner',
            name='other',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='core.othertypes', verbose_name='Субъект учета типа <иной тип>'),
        ),
        migrations.AddField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cust_post_to_cust_house', to='core.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddField(
            model_name='custplace2',
            name='upper_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.custplace2', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddField(
            model_name='custplace1',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custhouses', to='core.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AddField(
            model_name='custplace1',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custposts', to='core.custpost', verbose_name='Название поста'),
        ),
        migrations.AddField(
            model_name='custplace1',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus', to='core.rtu', verbose_name='Название РТУ'),
        ),
        migrations.AddField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cust_house_to_rtu', to='core.rtu', verbose_name='Вышестоящий т. орган'),
        ),
    ]
