# Generated by Django 3.2.16 on 2025-07-17 11:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая таможня', max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{4}000$')], verbose_name='Код т.органа')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Таможня',
                'verbose_name_plural': 'Таможни',
            },
        ),
        migrations.CreateModel(
            name='CustPlace1Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Субъект учета для т.органа 1-го типа',
                'verbose_name_plural': 'Субъекты учета для т.органа 1-го типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlace1Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Субъект эксплуатации для т.органа 1-го типа',
                'verbose_name_plural': 'Субъекты эксплуатации для т.органа 1-го типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlace2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('level', models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], max_length=1, verbose_name='Уровень т.органа')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Т.орган второго типа',
                'verbose_name_plural': 'Т.органы второго типа',
            },
        ),
        migrations.CreateModel(
            name='CustPlaceToLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_for_cust', models.BooleanField(default=False, verbose_name='Флаг приоритетности')),
            ],
            options={
                'verbose_name': 'Отношение т.органа к локации эксплуатации',
                'verbose_name_plural': 'Отношения т.органа к локации эксплуатации',
            },
        ),
        migrations.CreateModel(
            name='CustPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый пост', max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Таможенный пост',
                'verbose_name_plural': 'Таможенные посты',
            },
        ),
        migrations.CreateModel(
            name='DevCatsL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 1', max_length=255, unique=True, verbose_name='Название категории уровня 1')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 1 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 1 типов приборов',
            },
        ),
        migrations.CreateModel(
            name='DevCatsL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 2', max_length=255, unique=True, verbose_name='Название категории уровня 2')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 2 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 2 типов приборов',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, null=True, verbose_name='Серийный номер')),
                ('sub_type', models.CharField(default=None, max_length=255, null=True, verbose_name='Подтип')),
                ('is_si', models.BooleanField(default=False, null=True, verbose_name='СИ или индикатор')),
                ('note1', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание1')),
                ('note2', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание2')),
            ],
            options={
                'verbose_name': 'Техническое средство',
                'verbose_name_plural': 'Технические средства',
            },
        ),
        migrations.CreateModel(
            name='DevTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый прибор', max_length=255, verbose_name='Название прибора')),
                ('serial_flag', models.BooleanField(default=None, null=True, verbose_name='Признак сер.номера')),
                ('upper_dev_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак наличия вышестоящего девайса')),
                ('si_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак принадлежности к СИ')),
                ('sub_types', models.JSONField(blank=True, default=list, null=True, verbose_name='Допустимые подтипы')),
            ],
            options={
                'verbose_name': 'Объект типа прибора',
                'verbose_name_plural': 'Объекты типов приборов',
            },
        ),
        migrations.CreateModel(
            name='LocationOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ztk', models.BooleanField(default=False, verbose_name='Является ли ЗТК')),
            ],
            options={
                'verbose_name': 'объект локации',
                'verbose_name_plural': 'объекты локации',
            },
        ),
        migrations.CreateModel(
            name='Mmpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ММПО',
                'verbose_name_plural': 'объекты ММПО',
            },
        ),
        migrations.CreateModel(
            name='Oez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ОЭЗ',
                'verbose_name_plural': 'объекты ОЭЗ',
            },
        ),
        migrations.CreateModel(
            name='Ppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('tow_country', models.CharField(max_length=255, null=True, verbose_name='Сопредельное государство')),
            ],
            options={
                'verbose_name': 'объект пункта пропуска',
                'verbose_name_plural': 'объекты пунктов пропуска',
            },
        ),
        migrations.CreateModel(
            name='PprType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект типа пункта пропуска',
                'verbose_name_plural': 'объекты типа пунктов пропуска',
            },
        ),
        migrations.CreateModel(
            name='RelToDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_for_dev', models.BooleanField(default=False, verbose_name='Флаг приоритетности')),
            ],
            options={
                'verbose_name': 'объект промежутки',
                'verbose_name_plural': 'объекты промежутки',
            },
        ),
        migrations.CreateModel(
            name='Rtu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новое РТУ', max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{2}00000$')], verbose_name='Код т.органа')),
                ('address', models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес')),
                ('ztk_allowed', models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК')),
                ('standalone_allowed', models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации')),
            ],
            options={
                'verbose_name': 'Региональное таможенное управление',
                'verbose_name_plural': 'Региональные таможенные управления',
            },
        ),
        migrations.CreateModel(
            name='SourceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип источника имущества')),
            ],
            options={
                'verbose_name': 'Источник получения имущества',
                'verbose_name_plural': 'Источники получения имущества',
            },
        ),
        migrations.CreateModel(
            name='StatusTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип статуса по эксплуатации')),
            ],
            options={
                'verbose_name': 'Статус по эксплуатации',
                'verbose_name_plural': 'Статусы по эксплуатации',
            },
        ),
        migrations.CreateModel(
            name='Ztk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ЗТК',
                'verbose_name_plural': 'объекты ЗТК',
            },
        ),
        migrations.AddConstraint(
            model_name='ztk',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_ztk_title'),
        ),
        migrations.AddField(
            model_name='reltodev',
            name='to_dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_dev', to='core.device', verbose_name='прибор'),
        ),
        migrations.AddField(
            model_name='reltodev',
            name='to_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_relation', to='core.custplacetolocation', verbose_name='т.орган и место'),
        ),
        migrations.AddField(
            model_name='ppr',
            name='pptype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_pptype', to='core.pprtype', verbose_name='Тип п. пропуска'),
        ),
        migrations.AddConstraint(
            model_name='oez',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_oez_title'),
        ),
        migrations.AddConstraint(
            model_name='mmpo',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_mmpo_title'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='custplaces',
            field=models.ManyToManyField(through='core.CustPlaceToLocation', to='core.CustPlace1Use'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='mmpo',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmpos', to='core.mmpo', verbose_name='Название ММПО'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='oez',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oezs', to='core.oez', verbose_name='Название ОЭЗ'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='ppr',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pprs', to='core.ppr', verbose_name='Название п.пропуска'),
        ),
        migrations.AddField(
            model_name='locationofuse',
            name='ztk',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ztks', to='core.ztk', verbose_name='Название ЗТК'),
        ),
        migrations.AddField(
            model_name='devtypes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl2', verbose_name='Категория прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='cp1_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp1acc_to_dev', to='core.custplace1acc', verbose_name='Учетчик-т.о. 1-го типа'),
        ),
        migrations.AddField(
            model_name='device',
            name='cp2_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp2acc_to_dev', to='core.custplace2', verbose_name='Учетчик-т.о. 2-го типа'),
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_work',
            field=models.ManyToManyField(through='core.RelToDev', to='core.CustPlaceToLocation'),
        ),
        migrations.AddField(
            model_name='device',
            name='sour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_type_to_dev', to='core.sourcetypes', verbose_name='Источник собственности'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_use_to_dev', to='core.statustypes', verbose_name='Статус эксплуатации'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_type_to_dev_obj', to='core.devtypes', verbose_name='Тип прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий девайс'),
        ),
        migrations.AddField(
            model_name='devcatsl2',
            name='cat_l2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl1', verbose_name='Категория уровня 2 прибора'),
        ),
        migrations.AddField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cust_post_to_cust_house', to='core.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddField(
            model_name='custplacetolocation',
            name='cust_pl1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cp1', to='core.custplace1use', verbose_name='т. орган_1'),
        ),
        migrations.AddField(
            model_name='custplacetolocation',
            name='cust_pl2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cp2', to='core.custplace2', verbose_name='т. орган_2'),
        ),
        migrations.AddField(
            model_name='custplacetolocation',
            name='loc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_location', to='core.locationofuse', verbose_name='локация'),
        ),
        migrations.AddField(
            model_name='custplace2',
            name='upper_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.custplace2', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1use', to='core.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1use', to='core.custpost', verbose_name='Название поста'),
        ),
        migrations.AddField(
            model_name='custplace1use',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1use', to='core.rtu', verbose_name='Название РТУ'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1acc', to='core.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1acc', to='core.custpost', verbose_name='Название поста'),
        ),
        migrations.AddField(
            model_name='custplace1acc',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1acc', to='core.rtu', verbose_name='Название РТУ'),
        ),
        migrations.AddField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cust_house_to_rtu', to='core.rtu', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(fields=('to_rel', 'to_dev'), name='unique_to_rel_to_dev'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='uniq_main_for_dev'),
        ),
        migrations.AddConstraint(
            model_name='ppr',
            constraint=models.UniqueConstraint(fields=('pptype', 'title', 'tow_country'), name='unique_type_title'),
        ),
        migrations.AddConstraint(
            model_name='locationofuse',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ppr__isnull', True), ('mmpo__isnull', True), ('oez__isnull', True), models.Q(('ztk__isnull', True), _negated=True)), models.Q(('ppr__isnull', True), ('mmpo__isnull', True), models.Q(('oez__isnull', True), _negated=True), ('ztk__isnull', True)), models.Q(('ppr__isnull', True), models.Q(('mmpo__isnull', True), _negated=True), ('oez__isnull', True), ('ztk__isnull', True)), models.Q(models.Q(('ppr__isnull', True), _negated=True), ('mmpo__isnull', True), ('oez__isnull', True), ('ztk__isnull', True)), _connector='OR'), name='Loc_Nullable'),
        ),
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(fields=('cust_pl1', 'cust_pl2', 'loc'), name='unique_cp1_cp2_loc'),
        ),
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_cust', True)), fields=('cust_pl1',), name='uniq_main_for_cp1'),
        ),
        migrations.AddConstraint(
            model_name='custplace1use',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rtu__isnull', True), ('custhouse__isnull', True), models.Q(('custpost__isnull', True), _negated=True)), models.Q(('rtu__isnull', True), models.Q(('custhouse__isnull', True), _negated=True), ('custpost__isnull', True)), models.Q(models.Q(('rtu__isnull', True), _negated=True), ('custhouse__isnull', True), ('custpost__isnull', True)), _connector='OR'), name='CP1UseNullable'),
        ),
        migrations.AddConstraint(
            model_name='custplace1acc',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rtu__isnull', True), ('custhouse__isnull', True), models.Q(('custpost__isnull', True), _negated=True)), models.Q(('rtu__isnull', True), models.Q(('custhouse__isnull', True), _negated=True), ('custpost__isnull', True)), models.Q(models.Q(('rtu__isnull', True), _negated=True), ('custhouse__isnull', True), ('custpost__isnull', True)), _connector='OR'), name='CP1AccNullable'),
        ),
    ]
