# Generated by Django 3.2.16 on 2026-02-20 06:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый гос.контракт', max_length=255, unique=True, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер гос.контракта')),
                ('date_of', models.DateField(verbose_name='Дата заключения гос.контракта')),
                ('date_start', models.DateField(verbose_name='Дата начала действий по гос.контракту')),
                ('date_end', models.DateField(verbose_name='Дата окончания действий по гос.контракту')),
                ('multi', models.BooleanField(default=True, verbose_name='Признако однократности действи по контракту')),
            ],
            options={
                'verbose_name': 'Объект гос.контракта',
                'verbose_name_plural': 'Объекты гос.контрактов',
            },
        ),
        migrations.CreateModel(
            name='DevCatsL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 1', max_length=255, unique=True, verbose_name='Название категории уровня 1')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 1 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 1 типов приборов',
            },
        ),
        migrations.CreateModel(
            name='DevCatsL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 2', max_length=255, unique=True, verbose_name='Название категории уровня 2')),
                ('cat_l1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl1', verbose_name='Категория уровня 2 прибора')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 2 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 2 типов приборов',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=255, null=True, verbose_name='Серийный номер')),
                ('inventary', models.CharField(max_length=255, null=True, verbose_name='Инвентарный номер')),
                ('date_prod', models.DateField(blank=True, default=datetime.date(1990, 1, 1), verbose_name='Дата изготовления')),
                ('date_expl', models.DateField(blank=True, default=datetime.date(1991, 1, 1), verbose_name='Дата ввода')),
                ('warr_period', models.PositiveSmallIntegerField(default=24, verbose_name='Срок гарантии при поставке')),
                ('date_verif', models.DateField(blank=True, default=datetime.date(1992, 1, 1), null=True)),
                ('cat_number_f', models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер категории фактический')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Балансовая стоимость, руб.')),
                ('condition', models.BooleanField(default=True, null=True, verbose_name='Исправность')),
                ('sub_type', models.CharField(default=None, max_length=255, null=True, verbose_name='Подтип')),
                ('is_si', models.BooleanField(default=False, null=True, verbose_name='СИ или индикатор')),
                ('is_stud', models.BooleanField(default=False, verbose_name='Учебное ТС')),
                ('note1', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание1')),
                ('note2', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание2')),
                ('note3', models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание3')),
                ('cp1_acc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp1acc_to_dev', to='custplaces.custplace1acc', verbose_name='Учетчик-т.о. 1-го типа')),
                ('holder', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за экспл-ю')),
            ],
            options={
                'verbose_name': 'Техническое средство',
                'verbose_name_plural': 'Технические средства',
            },
        ),
        migrations.CreateModel(
            name='DTCPotential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contr_to_dev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_dev_to_contr', to='core.device', verbose_name='прибор')),
                ('dev_to_contr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='f_contr_to_dev', to='core.contracts', verbose_name='гос.контракт')),
            ],
            options={
                'verbose_name': 'объект промежутки',
                'verbose_name_plural': 'объекты промежутки',
            },
        ),
        migrations.CreateModel(
            name='ServiceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Вид действий')),
            ],
            options={
                'verbose_name': 'Вид действия',
                'verbose_name_plural': 'Виды действий',
            },
        ),
        migrations.CreateModel(
            name='SourceTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип источника имущества')),
            ],
            options={
                'verbose_name': 'Источник получения имущества',
                'verbose_name_plural': 'Источники получения имущества',
            },
        ),
        migrations.CreateModel(
            name='StatusTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип статуса по эксплуатации')),
            ],
            options={
                'verbose_name': 'Статус по эксплуатации',
                'verbose_name_plural': 'Статусы по эксплуатации',
            },
        ),
        migrations.CreateModel(
            name='RelToDev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_for_dev', models.BooleanField(default=False, verbose_name='Флаг приоритетности')),
                ('to_dev', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_dev', to='core.device', verbose_name='прибор')),
                ('to_rel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_relation', to='custplaces.custplacetolocation', verbose_name='т.орган и место')),
            ],
            options={
                'verbose_name': 'объект промежутки',
                'verbose_name_plural': 'объекты промежутки',
            },
        ),
        migrations.CreateModel(
            name='DTCReal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exact_moment', models.DateTimeField(auto_now_add=True, verbose_name='Точная дата и время реального участия прибора в гос.контракте')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_dtcp_to_dtcr', to='core.dtcpotential', verbose_name='Основание')),
            ],
            options={
                'verbose_name': 'объект промежутки',
                'verbose_name_plural': 'объекты промежутки',
            },
        ),
        migrations.CreateModel(
            name='DevTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новый прибора', max_length=255, verbose_name='Название прибора')),
                ('lifetime', models.PositiveSmallIntegerField(default=2, verbose_name='Срок службы')),
                ('serial_flag', models.BooleanField(default=None, null=True, verbose_name='Признак сер.номера')),
                ('upper_dev_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак наличия вышестоящего девайса')),
                ('si_flag', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак принадлежности к СИ')),
                ('sub_types', models.JSONField(blank=True, default=list, null=True, verbose_name='Допустимые подтипы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl2', verbose_name='Категория прибора')),
            ],
            options={
                'verbose_name': 'Объект типа прибора',
                'verbose_name_plural': 'Объекты типов приборов',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_work',
            field=models.ManyToManyField(through='core.RelToDev', to='custplaces.CustPlaceToLocation'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serv_to_dev', to='core.servicetypes', verbose_name='Статус по централизованному т.о./ремонту'),
        ),
        migrations.AddField(
            model_name='device',
            name='sour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_type_to_dev', to='core.sourcetypes', verbose_name='Источник собственности'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_use_to_dev', to='core.statustypes', verbose_name='Статус эксплуатации'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_type_to_dev_obj', to='core.devtypes', verbose_name='Тип прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий девайс'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(fields=('to_rel', 'to_dev'), name='unique_to_rel_to_dev'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='uniq_main_for_dev'),
        ),
        migrations.AddConstraint(
            model_name='dtcreal',
            constraint=models.UniqueConstraint(fields=('basis', 'exact_moment'), name='unique_dc_real'),
        ),
        migrations.AddConstraint(
            model_name='dtcpotential',
            constraint=models.UniqueConstraint(fields=('contr_to_dev', 'dev_to_contr'), name='unique_dc_p'),
        ),
    ]
