# Generated by Django 3.2.16 on 2025-06-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtypes',
            name='serial_flag',
            field=models.BooleanField(default=None, null=True, verbose_name='Признак сер.номера'),
        ),
    ]
