# Generated by Django 3.2.16 on 2025-03-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(default=None, max_length=255, verbose_name='Название1')),
                ('title2', models.CharField(default=None, max_length=255, verbose_name='Название2')),
            ],
            options={
                'verbose_name': 'объект',
                'verbose_name_plural': 'объекты',
            },
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(fields=('title1', 'title2'), name='unique_title'),
        ),
    ]
