# Generated by Django 3.2.16 on 2024-12-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custhouses', to='core.rtu'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custposts', to='core.rtu'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus', to='core.rtu'),
        ),
    ]
