# Generated by Django 3.2.16 on 2024-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custhouse',
            old_name='rtu_id',
            new_name='upper_id',
        ),
        migrations.RenameField(
            model_name='custpost',
            old_name='cust_house_id',
            new_name='upper_id',
        ),
        migrations.AddField(
            model_name='rtu',
            name='upper_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
