# Generated by Django 3.2.16 on 2026-02-18 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custplaces', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за экспл-ю'),
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_contrs',
            field=models.ManyToManyField(through='core.DevToContrs', to='core.Contracts'),
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_work',
            field=models.ManyToManyField(through='core.RelToDev', to='custplaces.CustPlaceToLocation'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serv_to_dev', to='core.servicetypes', verbose_name='Статус по централизованному т.о./ремонту'),
        ),
        migrations.AddField(
            model_name='device',
            name='sour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_type_to_dev', to='core.sourcetypes', verbose_name='Источник собственности'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_use_to_dev', to='core.statustypes', verbose_name='Статус эксплуатации'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_type_to_dev_obj', to='core.devtypes', verbose_name='Тип прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий девайс'),
        ),
        migrations.AddField(
            model_name='devcatsl2',
            name='cat_l1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl1', verbose_name='Категория уровня 2 прибора'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(fields=('to_rel', 'to_dev'), name='unique_to_rel_to_dev'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='uniq_main_for_dev'),
        ),
        migrations.AddConstraint(
            model_name='devtocontrs',
            constraint=models.UniqueConstraint(fields=('contr_to_dev', 'dev_to_contr'), name='unique_dev_contr'),
        ),
    ]
