# Generated by Django 3.2.16 on 2025-06-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devtypes',
            name='si_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак принадлежности к СИ'),
        ),
    ]
