# Generated by Django 3.2.16 on 2026-02-21 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custplaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за экспл-ю'),
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_contracts',
            field=models.ManyToManyField(through='core.DTCPotential', to='core.RelContrDoing'),
        ),
        migrations.AddField(
            model_name='device',
            name='rels_of_work',
            field=models.ManyToManyField(through='core.RelToDev', to='custplaces.CustPlaceToLocation'),
        ),
        migrations.AddField(
            model_name='device',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serv_to_dev', to='core.servicetypes', verbose_name='Статус по централизованному т.о./ремонту'),
        ),
        migrations.AddField(
            model_name='device',
            name='sour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='s_type_to_dev', to='core.sourcetypes', verbose_name='Источник собственности'),
        ),
        migrations.AddField(
            model_name='device',
            name='status_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_use_to_dev', to='core.statustypes', verbose_name='Статус эксплуатации'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_type_to_dev_obj', to='core.devtypes', verbose_name='Тип прибора'),
        ),
        migrations.AddField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий девайс'),
        ),
        migrations.AddField(
            model_name='devcatsl2',
            name='cat_l1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl1', verbose_name='Категория уровня 2 прибора'),
        ),
        migrations.AddConstraint(
            model_name='contracts',
            constraint=models.UniqueConstraint(fields=('title', 'number', 'date_of'), name='unique_tnd'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(fields=('to_rel', 'to_dev'), name='unique_to_rel_to_dev'),
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='uniq_main_for_dev'),
        ),
        migrations.AddConstraint(
            model_name='relcontrdoing',
            constraint=models.UniqueConstraint(fields=('to_doing', 'to_contract'), name='unique_dc'),
        ),
        migrations.AddConstraint(
            model_name='dtcreal',
            constraint=models.UniqueConstraint(fields=('basis', 'exact_moment'), name='unique_dc_real'),
        ),
        migrations.AddConstraint(
            model_name='dtcpotential',
            constraint=models.UniqueConstraint(fields=('dev', 'reltocd'), name='unique_dr'),
        ),
    ]
