# Generated by Django 3.2.16 on 2026-02-13 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='date_expl',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), verbose_name='Дата ввода'),
        ),
        migrations.AddField(
            model_name='device',
            name='date_prod',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), verbose_name='Дата изготовления'),
        ),
        migrations.AddField(
            model_name='device',
            name='is_stud',
            field=models.BooleanField(default=False, verbose_name='Учебное ТС'),
        ),
    ]
