# Generated by Django 3.2.16 on 2025-03-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sub_type',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Подтип'),
        ),
    ]
