# Generated by Django 3.2.16 on 2025-01-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ppr',
            name='unique_type_title',
        ),
        migrations.AddConstraint(
            model_name='ppr',
            constraint=models.UniqueConstraint(fields=('pptype', 'title', 'tow_country'), name='unique_type_title'),
        ),
    ]
