# Generated by Django 3.2.16 on 2024-12-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
    ]
