# Generated by Django 3.2.16 on 2025-01-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250108_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherTypes',
            new_name='SourceTypes',
        ),
        migrations.AlterModelOptions(
            name='sourcetypes',
            options={'verbose_name': 'Источник получения имущества', 'verbose_name_plural': 'Источники получения имущества'},
        ),
    ]
