# Generated by Django 3.2.16 on 2026-02-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20260213_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custplace2',
            name='upper_id',
        ),
        migrations.RemoveConstraint(
            model_name='custplacetolocation',
            name='unique_cp1_cp2_loc',
        ),
        migrations.RemoveField(
            model_name='custplacetolocation',
            name='cust_pl2',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cp2_acc',
        ),
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(fields=('cust_pl1', 'loc'), name='unique_cp_loc'),
        ),
        migrations.DeleteModel(
            name='CustPlace2',
        ),
    ]
