# Generated by Django 3.2.16 on 2025-06-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_devtypes_serial_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtypes',
            name='upper_dev_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак наличия вышестоящего девайса'),
        ),
    ]
