# Generated by Django 3.2.16 on 2025-03-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250314_1644'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test1',
            name='unique_title',
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(fields=('title1',), name='unique_title'),
        ),
    ]
