# Generated by Django 3.2.16 on 2025-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_device_note3'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='gk_flag',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Флаг вхождения в ГК'),
        ),
    ]
