# Generated by Django 3.2.16 on 2025-06-26 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_devtypes_si_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Si',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип по СИ')),
            ],
            options={
                'verbose_name': 'Объект типа по СИ',
                'verbose_name_plural': 'Объекты типов по СИ',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='si',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_si', to='core.si', verbose_name='Тип по СИ'),
        ),
    ]
