# Generated by Django 3.2.16 on 2024-12-12 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241212_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custhouse',
            options={'verbose_name': 'Таможня', 'verbose_name_plural': 'Таможни'},
        ),
        migrations.AlterModelOptions(
            name='custpost',
            options={'verbose_name': 'Таможенный пост', 'verbose_name_plural': 'Таможенные посты'},
        ),
        migrations.AlterModelOptions(
            name='rtu',
            options={'verbose_name': 'Региональное таможенное управление', 'verbose_name_plural': 'Региональные таможенные управления'},
        ),
        migrations.RemoveField(
            model_name='rtu',
            name='upper_id',
        ),
        migrations.AlterField(
            model_name='custhouse',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{8}$')], verbose_name='Код т.органа'),
        ),
        migrations.AlterField(
            model_name='custhouse',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cust_house_to_rtu', to='core.rtu', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{8}$')], verbose_name='Код т.органа'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='cust_post_to_cust_house', to='core.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AlterField(
            model_name='rtu',
            name='code',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{8}$')], verbose_name='Код т.органа'),
        ),
        migrations.AlterField(
            model_name='rtu',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
