# Generated by Django 3.2.16 on 2026-03-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_verif',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
