# Generated by Django 3.2.16 on 2026-08-21 21:17

import core.validators
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='date_end',
            field=models.DateField(validators=[core.validators.real_date], verbose_name='Дата окончания действий по гос.контракту'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date_of',
            field=models.DateField(validators=[core.validators.real_date], verbose_name='Дата заключения гос.контракта'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='date_start',
            field=models.DateField(validators=[core.validators.real_date], verbose_name='Дата начала действий по гос.контракту'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cat_number_f',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, validators=[core.validators.real_cat], verbose_name='Номер категории фактический (от 1 до 4, если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_expl',
            field=models.DateField(blank=True, default=datetime.date(1991, 1, 1), validators=[core.validators.real_date], verbose_name='Дата ввода в эксплуатацию первоначальная при поставке'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_prod',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), validators=[core.validators.real_date], verbose_name='Дата изготовления (выпуска, производства)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_verif',
            field=models.DateField(blank=True, default=None, null=True, validators=[core.validators.real_date], verbose_name='Дата окончания последней поверки (если было)'),
        ),
        migrations.AlterField(
            model_name='dtcreal',
            name='exact_moment',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[core.validators.real_date], verbose_name='Реальная реализация потенциального события с прибором по контракту'),
        ),
    ]
