# Generated by Django 3.2.16 on 2025-01-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_custhouse_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Обобщенный собственник первого типа', 'verbose_name_plural': 'Обобщенные собственники первого типа'},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='owner',
            new_name='owner1',
        ),
    ]
