# Generated by Django 3.2.16 on 2026-02-22 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtcreal',
            name='exact_moment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Точная дата и время реального действия  с прибором по контракту'),
        ),
    ]
