# Generated by Django 3.2.16 on 2024-12-13 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241212_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{5}000$')], verbose_name='Код т.органа'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа'),
        ),
        migrations.AlterField(
            model_name='rtu',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{2}00000$')], verbose_name='Код т.органа'),
        ),
    ]
