# Generated by Django 3.2.16 on 2025-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_devtypes_upper_dev_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='standalone_allowed',
            field=models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации'),
        ),
        migrations.AlterField(
            model_name='custplace2',
            name='standalone_allowed',
            field=models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации'),
        ),
        migrations.AlterField(
            model_name='rtu',
            name='standalone_allowed',
            field=models.BooleanField(default=True, verbose_name='Признак разрешения работать без локации'),
        ),
    ]
