# Generated by Django 3.2.16 on 2025-03-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_custplacetolocation_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий девайс'),
        ),
        migrations.AddField(
            model_name='devtypes',
            name='upper_dev_flag',
            field=models.BooleanField(blank=True, default=False, verbose_name='Признак наличия вышестоящего девайса'),
        ),
    ]
