# Generated by Django 3.2.16 on 2025-01-10 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250108_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustPlace1Acc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custhouse', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1acc', to='core.custhouse', verbose_name='Название таможни')),
                ('custpost', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1acc', to='core.custpost', verbose_name='Название поста')),
                ('rtu', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1acc', to='core.rtu', verbose_name='Название РТУ')),
            ],
        ),
    ]
