# Generated by Django 3.2.16 on 2026-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dtcreal_exact_moment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='title',
            field=models.CharField(default='Новый гос.контракт', max_length=255, verbose_name='Название'),
        ),
    ]
