# Generated by Django 3.2.16 on 2025-01-02 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250102_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Техническое средство', 'verbose_name_plural': 'Технические средства'},
        ),
        migrations.AddField(
            model_name='device',
            name='owner2',
            field=models.ForeignKey(default=433, on_delete=django.db.models.deletion.RESTRICT, related_name='device_to_owner2', to='core.custplace', verbose_name='Собственник второго типа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='owner1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='device_to_owner1', to='core.owner', verbose_name='Собственник первого типа'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='custhouse',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custhouses', to='core.custhouse', verbose_name='Название таможни'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='custpost',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custposts', to='core.custpost', verbose_name='Название поста'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='rtu',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus', to='core.rtu', verbose_name='Название РТУ'),
        ),
    ]
