# Generated by Django 3.2.16 on 2025-03-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250315_1323'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test1',
            name='unique_title',
        ),
    ]
