# Generated by Django 3.2.16 on 2026-06-14 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_device_date_verif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_expl',
            field=models.DateField(blank=True, default=datetime.date(1991, 1, 1), verbose_name='Дата ввода первичная с завода'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_verif',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания последней поверки (если было)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sub_type',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Подтип технического средства'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_type_to_dev_obj', to='core.devtypes', verbose_name='Тип технического средства'),
        ),
    ]
