# Generated by Django 3.2.16 on 2025-03-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250307_1228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custplacetolocation',
            old_name='is_main',
            new_name='is_main_for_cust',
        ),
        migrations.RenameField(
            model_name='reltodev',
            old_name='is_main',
            new_name='is_main_for_dev',
        ),
    ]
