# Generated by Django 3.2.16 on 2025-07-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_device_gk_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='gk_flag',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Флаг вхождения в ГК'),
        ),
    ]
