# Generated by Django 3.2.16 on 2024-12-14 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241213_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{7}$')], verbose_name='Код т.органа')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('upper_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.custplace', verbose_name='Вышестоящий т. орган')),
            ],
        ),
    ]
