# Generated by Django 3.2.16 on 2025-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_custplace1acc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='custplace1',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='custplace2',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='other',
        ),
        migrations.AlterModelOptions(
            name='custplace1acc',
            options={'verbose_name': 'Субъект учета из т.органа 1-го типа', 'verbose_name_plural': 'Субъекты учета из т.органа 1-го типа'},
        ),
        migrations.DeleteModel(
            name='CustPlace1',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
