# Generated by Django 3.2.16 on 2026-06-14 12:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20260614_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cat_number_f',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='Номер категории фактический (от 1 до 4, если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_expl',
            field=models.DateField(blank=True, default=datetime.date(1991, 1, 1), verbose_name='Дата ввода в эксплуатацию первоначальная при поставке'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_prod',
            field=models.DateField(blank=True, default=datetime.date(1990, 1, 1), verbose_name='Дата изготовления (выпуска, производства)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Должностное лицо, ответственное за эксплуатацию (если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='inventary',
            field=models.CharField(max_length=255, null=True, verbose_name='Инвентарный номер (если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='serial',
            field=models.CharField(max_length=255, null=True, verbose_name='Cерийный номер (если есть)'),
        ),
    ]
