# Generated by Django 3.2.16 on 2025-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250102_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace',
            options={'verbose_name': 'Обобщенный собственник второго типа', 'verbose_name_plural': 'Обобщенные собственники второго типа'},
        ),
        migrations.AddConstraint(
            model_name='owner',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('rtu__isnull', False), ('custhouse__isnull', True), ('custpost__isnull', True)), models.Q(('rtu__isnull', True), ('custhouse__isnull', False), ('custpost__isnull', True)), models.Q(('rtu__isnull', True), ('custhouse__isnull', True), ('custpost__isnull', False)), _connector='OR'), name='The uniqueness of a non-zero field among all fields'),
        ),
    ]
