# Generated by Django 3.2.16 on 2025-03-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_test1_unique_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='title1',
            field=models.CharField(default=None, max_length=255, unique=True, verbose_name='Название1'),
        ),
    ]
