# Generated by Django 3.2.16 on 2025-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20250610_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='custhouse',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='custplace2',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='custpost',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='rtu',
            name='address',
            field=models.CharField(blank=True, default='-', max_length=255, verbose_name='Почтовый адрес'),
        ),
    ]
