# Generated by Django 3.2.16 on 2025-06-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250610_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='title',
            field=models.CharField(default='Новая таможня', max_length=255, verbose_name='Название'),
        ),
    ]
