# Generated by Django 3.2.16 on 2024-12-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_custplace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace',
            options={'verbose_name': 'Таможенный орган', 'verbose_name_plural': 'Таможенные органы'},
        ),
        migrations.AlterField(
            model_name='custplace',
            name='level',
            field=models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], max_length=1, verbose_name='Уровень т.органа'),
        ),
    ]
