# Generated by Django 3.2.16 on 2025-03-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_test1_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test1',
            name='title1',
            field=models.CharField(default=None, max_length=255, verbose_name='Название1'),
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(fields=('title1',), name='unique_title'),
        ),
    ]
