# Generated by Django 3.2.16 on 2025-01-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250110_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace1acc',
            options={'verbose_name': 'Субъект учета для т.органа 1-го типа', 'verbose_name_plural': 'Субъекты учета для т.органа 1-го типа'},
        ),
        migrations.CreateModel(
            name='CustPlace1Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custhouse', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cs1use', to='core.custhouse', verbose_name='Название таможни')),
                ('custpost', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts1use', to='core.custpost', verbose_name='Название поста')),
                ('rtu', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtus1use', to='core.rtu', verbose_name='Название РТУ')),
            ],
            options={
                'verbose_name': 'Субъект эксплуатации для т.органа 1-го типа',
                'verbose_name_plural': 'Субъекты эксплуатации для т.органа 1-го типа',
            },
        ),
    ]
