# Generated by Django 3.2.16 on 2025-03-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250307_1338'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(fields=('to_rel', 'to_dev'), name='unique_to_rel_to_dev'),
        ),
    ]
