# Generated by Django 3.2.16 on 2025-01-02 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250102_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='code',
            field=models.CharField(max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^1\\d{4}000$')], verbose_name='Код т.органа'),
        ),
    ]
