# Generated by Django 3.2.16 on 2026-06-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custplaces', '0001_initial'),
        ('core', '0005_auto_20260614_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.BooleanField(default=True, null=True, verbose_name='Состояние по исправности на текущий день (включая все блоки и все нижестоящие приборы, если известно, да-исправно, нет-неисправно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Величина балансовой стоимости (если есть, отдельно от прочих), руб.'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cp1_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cp1acc_to_dev', to='custplaces.custplace1acc', verbose_name='Таможенный орган, в котором числится в оперативном управлении (на балансовом учете), либо на забалансовом учете'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_si',
            field=models.BooleanField(default=False, null=True, verbose_name='Является ли СИ конкретный экземпляр (да-СИ, нет-индикатор)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_stud',
            field=models.BooleanField(default=False, null=True, verbose_name='Яляется ли учебным конкретный экземпляр (да-учебный, нет-нет)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий прибор (если есть)'),
        ),
    ]
