# Generated by Django 3.2.16 on 2025-03-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250315_1331'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test1',
            name='unique_title',
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(condition=models.Q(('title2', 'qwerty')), fields=('title1',), name='unique_title'),
        ),
    ]
