# Generated by Django 3.2.16 on 2026-08-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custplaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20260614_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Должностное лицо, ответственное за эксплуатацию (только одно, если таковое есть, с его отделом),'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note1',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Примечение1 (район субъекта эксплуатации, если имеется и известно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note2',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Примечение2 (иные примечания, если имеется и известно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note3',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Примечение3 (сведения о месте следующей планируемой эксплуатации, если имеется и известно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rels_of_contracts',
            field=models.ManyToManyField(through='core.DTCPotential', to='core.RelContrDoing', verbose_name='Информация по потенциальному вхождению прибора в гос.контракты'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rels_of_work',
            field=models.ManyToManyField(through='core.RelToDev', to='custplaces.CustPlaceToLocation', verbose_name='Какой там.орган и в каком месте эксплуатирует прибор'),
        ),
        migrations.AlterField(
            model_name='device',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serv_to_dev', to='core.servicetypes', verbose_name='Статус по централизованному т.о./ремонту, подлежит ли прибор'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_use_to_dev', to='core.statustypes', verbose_name='Статус по эксплуатации'),
        ),
        migrations.AlterField(
            model_name='device',
            name='upper_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_upper_level', to='core.device', verbose_name='Вышестоящий прибор (если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='warr_period',
            field=models.PositiveSmallIntegerField(default=24, verbose_name='Срок гарантии при поставке (месяцев)'),
        ),
        migrations.AlterField(
            model_name='dtcpotential',
            name='dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_dev_to_doing', to='core.device', verbose_name='прибор'),
        ),
        migrations.AlterField(
            model_name='dtcreal',
            name='basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dtcp_to_dtcr', to='core.dtcpotential', verbose_name='Основание'),
        ),
        migrations.AlterField(
            model_name='reltodev',
            name='to_dev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_dev', to='core.device', verbose_name='прибор'),
        ),
    ]
