# Generated by Django 3.2.16 on 2025-01-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20250110_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mmpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ММПО',
                'verbose_name_plural': 'объекты ММПО',
            },
        ),
        migrations.CreateModel(
            name='Oez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ОЭЗ',
                'verbose_name_plural': 'объекты ОЭЗ',
            },
        ),
        migrations.CreateModel(
            name='Ztk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'объект ЗТК',
                'verbose_name_plural': 'объекты ЗТК',
            },
        ),
        migrations.AlterModelOptions(
            name='ppr',
            options={'verbose_name': 'объект пункта пропуска', 'verbose_name_plural': 'объекты пунктов пропуска'},
        ),
        migrations.AddConstraint(
            model_name='ztk',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_ztk_title'),
        ),
        migrations.AddConstraint(
            model_name='oez',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_oez_title'),
        ),
        migrations.AddConstraint(
            model_name='mmpo',
            constraint=models.UniqueConstraint(fields=('title',), name='unique_mmpo_title'),
        ),
    ]
