# Generated by Django 3.2.16 on 2025-06-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_custhouse_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='note1',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание1'),
        ),
        migrations.AddField(
            model_name='device',
            name='note2',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Примечание2'),
        ),
    ]
