# Generated by Django 3.2.16 on 2025-01-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_custhouse_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='owner',
            name='The uniqueness of a non-zero field among all fields',
        ),
    ]
