# Generated by Django 3.2.16 on 2025-01-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_owner_the uniqueness of a non-zero field among all fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_house_to_rtu', to='core.rtu', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cust_post_to_cust_house', to='core.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
    ]
