# Generated by Django 3.2.16 on 2026-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260809_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='inventary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Инвентарный номер (если есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note2',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Примечение2 (иные примечания, если имеется и известно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='note3',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Примечение3 (сведения о месте следующей планируемой эксплуатации, если имеется и известно)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='sub_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Подтип технического средства'),
        ),
    ]
