# Generated by Django 3.2.16 on 2025-06-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250614_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevCatsL1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 1', max_length=255, unique=True, verbose_name='Название категории уровня 1')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 1 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 1 типов приборов',
            },
        ),
        migrations.CreateModel(
            name='DevCatsL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Новая категория уровня 2', max_length=255, unique=True, verbose_name='Название категории уровня 2')),
                ('cat_l2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl1', verbose_name='Категория уровня 2 прибора')),
            ],
            options={
                'verbose_name': 'Объект категории уровня 2 типа прибора',
                'verbose_name_plural': 'Объекты категории уровня 2 типов приборов',
            },
        ),
        migrations.AlterField(
            model_name='devtypes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dev_cat_to_dev_type', to='core.devcatsl2', verbose_name='Категория прибора'),
        ),
        migrations.DeleteModel(
            name='DevCats',
        ),
    ]
