# Generated by Django 3.2.16 on 2025-03-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250315_1341'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test1',
            name='unique_title',
        ),
        migrations.AddField(
            model_name='test1',
            name='title3',
            field=models.CharField(default=None, max_length=255, verbose_name='Название3'),
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(condition=models.Q(('title3', 'qwerty')), fields=('title1', 'title2'), name='unique_title'),
        ),
    ]
