# Generated by Django 3.2.16 on 2025-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20250117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='custplace1use',
            name='may_have_ztk',
            field=models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК'),
        ),
    ]
