# Generated by Django 3.2.16 on 2024-12-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_device_site_keeper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
