# Generated by Django 3.2.16 on 2024-12-21 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_device_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='object_id',
        ),
    ]
