# Generated by Django 3.2.16 on 2025-03-15 11:05

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250315_1348'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='test1',
            name='unique_title',
        ),
        migrations.AddConstraint(
            model_name='test1',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('title1', 'title2'), name='unique_title'),
        ),
    ]
