# Generated by Django 3.2.16 on 2025-01-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_custplace1use_may_have_ztk'),
    ]

    operations = [
        migrations.AddField(
            model_name='custplace2',
            name='may_have_ztk',
            field=models.BooleanField(default=False, verbose_name='Признак разрешения работать в ЗТК'),
        ),
    ]
