# Generated by Django 3.2.16 on 2026-08-15 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_auto_20260809_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='holder',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_man_to_dev', to=settings.AUTH_USER_MODEL, verbose_name='Должностное лицо, ответственное за эксплуатацию (только одно, если таковое есть)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='rels_of_contracts',
            field=models.ManyToManyField(through='core.DTCPotential', to='core.RelContrDoing', verbose_name='Потенциальное вхождение прибора в гос.контракты'),
        ),
    ]
