# Generated by Django 3.2.16 on 2025-01-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250102_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='upper_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cust_house_to_rtu', to='core.rtu', verbose_name='Вышестоящий т. орган'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='upper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cust_post_to_cust_house', to='core.custhouse', verbose_name='Вышестоящий т. орган'),
        ),
    ]
