# Generated by Django 3.2.16 on 2026-08-16 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260815_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtcreal',
            name='exact_moment',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Момент реального события с прибором по контракту'),
        ),
    ]
