# Generated by Django 3.2.16 on 2025-01-17 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_custplace2_may_have_ztk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custplace1use',
            old_name='may_have_ztk',
            new_name='ztk_allowed',
        ),
        migrations.RenameField(
            model_name='custplace2',
            old_name='may_have_ztk',
            new_name='ztk_allowed',
        ),
    ]
