# Generated by Django 3.2.16 on 2025-03-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250315_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test1',
        ),
        migrations.RemoveField(
            model_name='custplace1acc',
            name='standalone_allowed',
        ),
        migrations.RemoveField(
            model_name='custplace1acc',
            name='ztk_allowed',
        ),
    ]
