# Generated by Django 3.2.16 on 2024-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20241221_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='custhouse',
            name='upper_level',
            field=models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], default=1, max_length=1, verbose_name='Уровень вышестоящего т.органа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custpost',
            name='upper_level',
            field=models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], default=1, max_length=1, verbose_name='Уровень вышестоящего т.органа'),
            preserve_default=False,
        ),
    ]
