# Generated by Django 3.2.16 on 2025-01-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250102_2137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustPlace',
            new_name='CustPlace2',
        ),
        migrations.AlterModelOptions(
            name='custplace2',
            options={'verbose_name': 'Обобщенный объект т.органа второго типа', 'verbose_name_plural': 'Обобщенные объекты т.органа второго типа'},
        ),
    ]
