# Generated by Django 3.2.16 on 2025-03-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250315_1536'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='custplacetolocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_cust', True)), fields=('cust_pl1',), name='uniq_main_for_cp1'),
        ),
    ]
