# Generated by Django 3.2.16 on 2025-01-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250117_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationOfUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmpo', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mmpos', to='core.mmpo', verbose_name='Название ММПО')),
                ('oez', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oezs', to='core.oez', verbose_name='Название ОЭЗ')),
                ('ppr', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pprs', to='core.ppr', verbose_name='Название п.пропуска')),
                ('ztk', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ztks', to='core.ztk', verbose_name='Название ЗТК')),
            ],
            options={
                'verbose_name': 'объект локации',
                'verbose_name_plural': 'объекты локации',
            },
        ),
    ]
