# Generated by Django 3.2.16 on 2024-12-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20241222_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custhouse',
            name='upper_level',
            field=models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], max_length=1, null=True, verbose_name='Уровень вышестоящего т.органа'),
        ),
        migrations.AlterField(
            model_name='custpost',
            name='upper_level',
            field=models.CharField(choices=[('1', 'РТУ'), ('2', 'Таможня'), ('3', 'Пост')], max_length=1, null=True, verbose_name='Уровень вышестоящего т.органа'),
        ),
    ]
