# Generated by Django 3.2.16 on 2025-01-03 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250103_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owner',
            new_name='CustPlace1',
        ),
    ]
