# Generated by Django 3.2.16 on 2024-12-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20241222_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_keeper',
            name='title',
        ),
        migrations.AlterField(
            model_name='custpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
