# Generated by Django 3.2.16 on 2025-01-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_locationofuse'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustPlaceToLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Флаг приоритетности')),
                ('cust_pl1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cp1', to='core.custplace1use', verbose_name='т. орган_1')),
                ('cust_pl2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_cp2', to='core.custplace2', verbose_name='т. орган_2')),
                ('loc', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_location', to='core.locationofuse', verbose_name='локация')),
            ],
            options={
                'verbose_name': 'Отношение т.органа к локации эксплуатации',
                'verbose_name_plural': 'Отношения т.органа к локации эксплуатации',
            },
        ),
    ]
