# Generated by Django 3.2.16 on 2025-01-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_owner_custplace1'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип обобщенного объекта собственника',
                'verbose_name_plural': 'Типы обобщенных объектов собственника',
            },
        ),
    ]
