# Generated by Django 3.2.16 on 2025-03-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_custplacetolocation_uniq_main_for_cp1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='umiq_main_for_dev'),
        ),
    ]
