# Generated by Django 3.2.16 on 2025-01-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_custplacetolocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationofuse',
            name='custplaces',
            field=models.ManyToManyField(through='core.CustPlaceToLocation', to='core.CustPlace1Use'),
        ),
    ]
