# Generated by Django 3.2.16 on 2025-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_reltodev_umiq_main_for_dev'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reltodev',
            name='umiq_main_for_dev',
        ),
        migrations.AddConstraint(
            model_name='reltodev',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_for_dev', True)), fields=('to_dev',), name='uniq_main_for_dev'),
        ),
    ]
