# Generated by Django 3.2.16 on 2024-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20241222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custplace',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
