# Generated by Django 3.2.16 on 2025-01-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_ownertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custplace1', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces1', to='core.custplace1', verbose_name='Собственник типа <т.орган первого типа>')),
                ('custplace2', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces2', to='core.custplace2', verbose_name='Собственник типа <т.орган второго типа>')),
            ],
            options={
                'verbose_name': 'Обобщенный объект собственника',
                'verbose_name_plural': 'Обобщенные объекты собственника',
            },
        ),
        migrations.DeleteModel(
            name='OwnerType',
        ),
    ]
