# Generated by Django 3.2.16 on 2025-01-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_locationofuse_custplaces'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custplacetolocation',
            unique_together={('cust_pl1', 'cust_pl2', 'loc', 'is_main')},
        ),
    ]
