# Generated by Django 3.2.16 on 2024-12-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_custplace_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='site_keeper',
        ),
        migrations.AddField(
            model_name='custhouse',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='custpost',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cust_post_to_cust_house', to='core.owner', verbose_name='Собственник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rtu',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.owner'),
            preserve_default=False,
        ),
    ]
