# Generated by Django 3.2.16 on 2025-01-03 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20250103_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosgrTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Вариант передачи')),
            ],
            options={
                'verbose_name': 'Вид передачи из Росгранстроя к т.о.',
                'verbose_name_plural': 'Виды передачи из Росгранстроя к т.о.',
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='rosgranstroy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosgrs', to='core.rosgrtypes', verbose_name='Собственник типа <Росгранстрой какого-то типа передачи>'),
        ),
    ]
