# Generated by Django 3.2.16 on 2025-01-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20250103_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace1',
            options={'verbose_name': 'Обобщенный объект т.органа первого типа', 'verbose_name_plural': 'Обобщенные объекты т.органа первого типа'},
        ),
    ]
