# Generated by Django 3.2.16 on 2025-01-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_custplace1_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner1',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner2',
        ),
    ]
