# Generated by Django 3.2.16 on 2025-01-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_owner_rosgranstroy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace1',
            options={'verbose_name': 'Объект т.органа первого типа', 'verbose_name_plural': 'Объекты т.органа первого типа'},
        ),
        migrations.AlterModelOptions(
            name='custplace2',
            options={'verbose_name': 'Объект т.органа второго типа', 'verbose_name_plural': 'Объекты т.органа второго типа'},
        ),
        migrations.AlterModelOptions(
            name='rosgrtypes',
            options={'verbose_name': 'Тип получения от  Росгранстроя', 'verbose_name_plural': 'Типы получения от Росгранстроя'},
        ),
    ]
