# Generated by Django 3.2.16 on 2025-01-03 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250103_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Объект собственника', 'verbose_name_plural': 'Объекты собственника'},
        ),
    ]
