# Generated by Django 3.2.16 on 2025-01-03 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_owner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='rosgranstroy',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosgrs', to='core.rosgrtypes', verbose_name='Собственник типа <Росгранстрой>'),
        ),
    ]
