# Generated by Django 3.2.16 on 2025-01-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_owner_rosgranstroy'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Тип источника собственности')),
            ],
            options={
                'verbose_name': 'Объект источника собственности',
                'verbose_name_plural': 'Объекты источника собственности',
            },
        ),
        migrations.RemoveField(
            model_name='owner',
            name='rosgranstroy',
        ),
        migrations.DeleteModel(
            name='RosgrTypes',
        ),
        migrations.AddField(
            model_name='owner',
            name='other',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='core.othertypes', verbose_name='Собственник типа <иной тип>'),
        ),
    ]
