# Generated by Django 3.2.16 on 2025-01-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20250103_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='othertypes',
            options={'verbose_name': 'Иной источник собственности', 'verbose_name_plural': 'Иные источники собственности'},
        ),
    ]
