# Generated by Django 3.2.16 on 2025-01-04 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_othertypes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custplace1',
            options={'verbose_name': 'Т.орган первого типа', 'verbose_name_plural': 'Т.органы первого типа'},
        ),
        migrations.AlterModelOptions(
            name='custplace2',
            options={'verbose_name': 'Т.орган второго типа', 'verbose_name_plural': 'Т.органы второго типа'},
        ),
        migrations.AlterModelOptions(
            name='othertypes',
            options={'verbose_name': 'Иной источник получения имущества', 'verbose_name_plural': 'Иные источники получения имущества'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Субъект учета т.с.', 'verbose_name_plural': 'Субъект учета т.с.'},
        ),
        migrations.AlterField(
            model_name='othertypes',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Тип источника имущества'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='custplace1',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces1', to='core.custplace1', verbose_name='Субъект учета типа <т.орган первого типа>'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='custplace2',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custplaces2', to='core.custplace2', verbose_name='Субъект учета типа <т.орган второго типа>'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='other',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='others', to='core.othertypes', verbose_name='Субъект учета типа <иной тип>'),
        ),
    ]
