# Generated by Django 3.2.16 on 2025-01-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20250104_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ppr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pptype', models.CharField(choices=[('1', 'АПП'), ('2', 'ВПП')], max_length=1, verbose_name='Тип п. пропуска')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Пункт пропуска',
                'verbose_name_plural': 'Пункты пропуска',
            },
        ),
    ]
