# Generated by Django 3.2.16 on 2025-01-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ppr'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppr',
            name='tow_country',
            field=models.CharField(max_length=255, null=True, verbose_name='Сопредельное государство'),
        ),
        migrations.AlterField(
            model_name='ppr',
            name='pptype',
            field=models.CharField(choices=[('1', 'АПП'), ('2', 'ВПП'), ('3', 'ЖДПП'), ('4', 'МПП'), ('5', 'ППП'), ('6', 'РПП'), ('7', 'СПП')], max_length=1, verbose_name='Тип п. пропуска'),
        ),
    ]
